### ISSUE TITLE
Can't connect to the kernel

### ISSUE THREAD

**Issue by mrf345** [jackos/gobook#7]
Hello,

I'm running Ubuntu 20.04 and have go installed through the snap store. I keep getting `Please wait for the gokernel to start`

![kernel_not_connecting](https://user-images.githubusercontent.com/26286907/147857576-77248c78-62cf-494a-80ff-118dd6e4a867.gif)

Found a quick workaround, starting the kernel manually `gokernel`

Thanks for the awesome extension!

**Comment by jackos** [comment]
Hi @mrf345 this will be something to do with installation from the snap store I'd say, I'm working on another version that works with multiple languages where the 'gokernel` isn't required at all which will resolve this issue, but I'll leave this open while I'm still working on that

**Comment by jackos** [comment]
@mrf345 I have moved this extension to `hackdown`, it doesn't use an external kernel now, it just uses your local `Go` toolchain. It's also much faster, more lightweight, supports importing packages, multiple languages and a couple extra features. Check it out and let me know what you think.
